// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfdSx64-DkexqQv1AsXB1ibFPyIwn6G7A',
    appId: '1:202803300218:web:105d8b56f4ec801b1cf8c3',
    messagingSenderId: '202803300218',
    projectId: 'flutterfirebase1-9168c',
    authDomain: 'flutterfirebase1-9168c.firebaseapp.com',
    databaseURL: 'https://flutterfirebase1-9168c-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfirebase1-9168c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-m5yoIlVqk-J49Wy19jFczpg0kYVrtgk',
    appId: '1:202803300218:android:a102608fd7e5a8041cf8c3',
    messagingSenderId: '202803300218',
    projectId: 'flutterfirebase1-9168c',
    databaseURL: 'https://flutterfirebase1-9168c-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfirebase1-9168c.appspot.com',
  );
}
